from backend.database.client import db_available, get_client

SEED_COLLEGES = [
    {
        "id": 1,
        "name": "IIT Kharagpur",
        "location": "Kharagpur",
        "state": "West Bengal",
        "type": "govt",
        "nirf_rank": 6,
        "avg_package": "18.5",
        "placement_pct": 92,
        "rating": 4.7,
        "streams": ["Engineering", "Sciences", "Architecture", "Management"],
        "top_recruiters": ["Google", "Microsoft", "Amazon", "Goldman Sachs"],
        "min_12th_marks": 75,
        "website": "iitkgp.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1951",
        "description": "India's first IIT and among its largest, known for research, fests and alumni.",
        "pros": [
            "Huge alumni & research network",
            "Excellent placements & brand",
            "Vibrant campus life (Spring Fest, Kshitij)",
        ],
        "cons": ["Remote location (Kharagpur)", "Very large, spread-out campus"],
    },
    {
        "id": 2,
        "name": "Jadavpur University",
        "location": "Kolkata",
        "state": "West Bengal",
        "type": "govt",
        "nirf_rank": 34,
        "avg_package": "9.0",
        "placement_pct": 88,
        "rating": 4.4,
        "streams": ["Engineering", "Arts", "Science", "Commerce"],
        "top_recruiters": ["TCS", "Infosys", "Cognizant", "Wipro"],
        "min_12th_marks": 70,
        "website": "jaduniv.edu.in",
        "affiliation": "State University, Govt. of West Bengal",
        "founded": "1955",
        "description": "Premier public university in Kolkata with strong engineering, arts & science.",
        "pros": [
            "Very low fees, high ROI",
            "Strong faculty & research",
            "Excellent CSE/ECE placements",
        ],
        "cons": ["Aging infrastructure", "Admission highly competitive"],
    },
    {
        "id": 3,
        "name": "IIEST Shibpur",
        "location": "Howrah",
        "state": "West Bengal",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "8.2",
        "placement_pct": 85,
        "rating": 4.2,
        "streams": ["Engineering", "Architecture", "Sciences"],
        "top_recruiters": ["L&T", "TCS", "Accenture", "IBM"],
        "min_12th_marks": 72,
        "website": "iiests.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1856",
        "description": "One of India's oldest engineering institutions, now an INI near Kolkata.",
        "pros": [
            "Historic, well-regarded brand",
            "Good core-engineering placements",
            "Government-funded, low fees",
        ],
        "cons": ["Smaller campus", "Fewer CS/IT recruiters than IITs"],
    },
    {
        "id": 4,
        "name": "NIT Durgapur",
        "location": "Durgapur",
        "state": "West Bengal",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "7.6",
        "placement_pct": 83,
        "rating": 4.1,
        "streams": ["Engineering", "Sciences", "Management"],
        "top_recruiters": ["TCS", "Wipro", "Capgemini", "Infosys"],
        "min_12th_marks": 70,
        "website": "nitdgp.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1960",
        "description": "Leading NIT in West Bengal with solid engineering programs.",
        "pros": [
            "National brand, low fees",
            "Decent core & IT placements",
            "Active student clubs",
        ],
        "cons": ["Limited higher-end packages", "Smaller than metro campuses"],
    },
    {
        "id": 5,
        "name": "NIT Trichy",
        "location": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "type": "govt",
        "nirf_rank": 10,
        "avg_package": "11.2",
        "placement_pct": 90,
        "rating": 4.6,
        "streams": ["Engineering", "Management", "Sciences", "Architecture"],
        "top_recruiters": ["Microsoft", "Amazon", "Adobe", "Qualcomm"],
        "min_12th_marks": 75,
        "website": "nitt.edu",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1964",
        "description": "Consistently India's top NIT, excellent placements across branches.",
        "pros": [
            "Top NIRF rank among NITs",
            "Outstanding placements & infrastructure",
            "Strong alumni network",
        ],
        "cons": ["Highly competitive", "Large batch sizes"],
    },
    {
        "id": 6,
        "name": "BITS Pilani",
        "location": "Pilani",
        "state": "Rajasthan",
        "type": "private",
        "nirf_rank": 20,
        "avg_package": "18.0",
        "placement_pct": 94,
        "rating": 4.5,
        "streams": ["Engineering", "Sciences", "Management", "Pharmacy"],
        "top_recruiters": ["Google", "Uber", "Goldman Sachs", "Adobe"],
        "min_12th_marks": 80,
        "website": "bits-pilani.ac.in",
        "affiliation": "Deemed University (Private)",
        "founded": "1964",
        "description": "Prestigious private institute famed for freedom, entrepreneurship & placements.",
        "pros": [
            "No attendance policy",
            "Excellent peer group & recruiters",
            "Strong startup culture",
        ],
        "cons": ["High tuition fees", "Competitive academics"],
    },
    {
        "id": 7,
        "name": "Delhi University",
        "location": "Delhi",
        "state": "Delhi",
        "type": "govt",
        "nirf_rank": 36,
        "avg_package": "7.0",
        "placement_pct": 80,
        "rating": 4.3,
        "streams": ["Arts", "Commerce", "Science", "Law"],
        "top_recruiters": ["Deloitte", "EY", "KPMG", "TCS"],
        "min_12th_marks": 65,
        "website": "du.ac.in",
        "affiliation": "Central University, GoI",
        "founded": "1922",
        "description": "India's largest & most prestigious public university with top colleges.",
        "pros": [
            "Iconic brand & alumni",
            "Very low fees",
            "Great arts/commerce/science colleges",
        ],
        "cons": [
            "North Campus most sought-after",
            "Limited central placements for some courses",
        ],
    },
    {
        "id": 8,
        "name": "Anna University",
        "location": "Chennai",
        "state": "Tamil Nadu",
        "type": "govt",
        "nirf_rank": 14,
        "avg_package": "8.0",
        "placement_pct": 84,
        "rating": 4.2,
        "streams": ["Engineering", "Technology", "Architecture", "Management"],
        "top_recruiters": ["TCS", "CTS", "Zoho", "Infosys"],
        "min_12th_marks": 70,
        "website": "annauniv.edu",
        "affiliation": "State University, Govt. of Tamil Nadu",
        "founded": "1978",
        "description": "Tamil Nadu's apex technical university; top engineering admissions.",
        "pros": [
            "Strong regional brand",
            "Good placements in South India",
            "Research-oriented",
        ],
        "cons": ["Affiliated-college quality varies", "Large bureaucracy"],
    },
    {
        "id": 9,
        "name": "VIT Vellore",
        "location": "Vellore",
        "state": "Tamil Nadu",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "6.0",
        "placement_pct": 86,
        "rating": 4.1,
        "streams": ["Engineering", "Technology", "Science", "Management"],
        "top_recruiters": ["TCS", "Infosys", "Microsoft", "Paypal"],
        "min_12th_marks": 60,
        "website": "vit.ac.in",
        "affiliation": "Deemed University (Private)",
        "founded": "1984",
        "description": "Large private university known for smooth placements & global tie-ups.",
        "pros": [
            "Very high placement volume",
            "Good infrastructure",
            "Category-based admission",
        ],
        "cons": ["Strict rules & heavy fees", "Large student population"],
    },
    {
        "id": 10,
        "name": "IIT Bombay",
        "location": "Mumbai",
        "state": "Maharashtra",
        "type": "govt",
        "nirf_rank": 3,
        "avg_package": "22.0",
        "placement_pct": 93,
        "rating": 4.8,
        "streams": ["Engineering", "Sciences", "Design", "Management"],
        "top_recruiters": ["Google", "Microsoft", "Apple", "Goldman Sachs"],
        "min_12th_marks": 75,
        "website": "iitb.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1958",
        "description": "India's top IIT for technology, entrepreneurship and research.",
        "pros": [
            "Best brand for tech/startups",
            "Outstanding packages & alumni",
            "Mumbai location",
        ],
        "cons": ["Extremely competitive", "Costly city, demanding workload"],
    },
    {
        "id": 11,
        "name": "IIT Delhi",
        "location": "New Delhi",
        "state": "Delhi",
        "type": "govt",
        "nirf_rank": 4,
        "avg_package": "20.0",
        "placement_pct": 92,
        "rating": 4.8,
        "streams": ["Engineering", "Sciences", "Management", "Design"],
        "top_recruiters": ["Amazon", "Adobe", "Qualcomm", "Uber"],
        "min_12th_marks": 75,
        "website": "iitd.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1961",
        "description": "Premier IIT in the capital with elite research & placements.",
        "pros": [
            "Top recruiters & research",
            "Delhi location & network",
            "Strong entrepreneurial ecosystem",
        ],
        "cons": ["High competition", "Dense, fast-paced campus"],
    },
    {
        "id": 12,
        "name": "Jawaharlal Nehru University",
        "location": "New Delhi",
        "state": "Delhi",
        "type": "govt",
        "nirf_rank": 9,
        "avg_package": "9.0",
        "placement_pct": 78,
        "rating": 4.3,
        "streams": ["Arts", "Social Sciences", "Languages", "Sciences"],
        "top_recruiters": ["UN Bodies", "Think Tanks", "Civil Services", "Academia"],
        "min_12th_marks": 60,
        "website": "jnu.ac.in",
        "affiliation": "Central University, GoI",
        "founded": "1969",
        "description": "Renowned for social sciences, languages and a vibrant intellectual culture.",
        "pros": [
            "Low fees, rich academics",
            "Excellent for humanities/social sciences",
            "Iconic campus life",
        ],
        "cons": [
            "Limited engineering/placement focus",
            "Occasional campus disruptions",
        ],
    },
    {
        "id": 13,
        "name": "Banaras Hindu University",
        "location": "Varanasi",
        "state": "Uttar Pradesh",
        "type": "govt",
        "nirf_rank": 35,
        "avg_package": "7.5",
        "placement_pct": 81,
        "rating": 4.2,
        "streams": ["Arts", "Science", "Engineering", "Medical", "Commerce"],
        "top_recruiters": ["TCS", "Wipro", "Infosys", "BYJU'S"],
        "min_12th_marks": 65,
        "website": "bhu.ac.in",
        "affiliation": "Central University, GoI",
        "founded": "1916",
        "description": "Historic central university in Varanasi with diverse programs.",
        "pros": [
            "Vast, green campus",
            "Low fees, broad offerings",
            "Strong medical & sciences",
        ],
        "cons": [
            "Slow administrative processes",
            "Placements uneven outside top branches",
        ],
    },
    {
        "id": 14,
        "name": "SRM Institute of Science & Technology",
        "location": "Chennai",
        "state": "Tamil Nadu",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "5.0",
        "placement_pct": 82,
        "rating": 4.0,
        "streams": ["Engineering", "Technology", "Management", "Medicine"],
        "top_recruiters": ["TCS", "CTS", "Wipro", "Capgemini"],
        "min_12th_marks": 55,
        "website": "srmist.edu.in",
        "affiliation": "Deemed University (Private)",
        "founded": "1985",
        "description": "Major private university with large campuses and decent placements.",
        "pros": ["Good IT placements", "Modern infrastructure", "Multiple campuses"],
        "cons": ["High fees", "Variable branch quality"],
    },
    {
        "id": 15,
        "name": "Manipal Academy of Higher Education",
        "location": "Manipal",
        "state": "Karnataka",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "7.0",
        "placement_pct": 87,
        "rating": 4.3,
        "streams": ["Engineering", "Medical", "Pharmacy", "Allied Health"],
        "top_recruiters": ["Siemens", "Bosch", "TCS", "Philips"],
        "min_12th_marks": 60,
        "website": "manipal.edu",
        "affiliation": "Deemed University (Private)",
        "founded": "1953",
        "description": "Well-known private deemed university with strong health sciences.",
        "pros": [
            "Excellent medical & engineering",
            "Picturesque campus",
            "Good international exposure",
        ],
        "cons": ["High tuition", "Competitive for top branches"],
    },
    {
        "id": 16,
        "name": "Amrita Vishwa Vidyapeetham",
        "location": "Coimbatore",
        "state": "Tamil Nadu",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "6.0",
        "placement_pct": 85,
        "rating": 4.2,
        "streams": ["Engineering", "Medical", "Sciences", "Management"],
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Cognizant"],
        "min_12th_marks": 60,
        "website": "amrita.edu",
        "affiliation": "Deemed University (Private)",
        "founded": "1994",
        "description": "Values-based private university strong in engineering & health.",
        "pros": [
            "Good placements & discipline",
            "Strong research centers",
            "Multi-state campuses",
        ],
        "cons": ["Strict rules", "High fees"],
    },
    {
        "id": 17,
        "name": "University of Calcutta",
        "location": "Kolkata",
        "state": "West Bengal",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "5.5",
        "placement_pct": 76,
        "rating": 4.1,
        "streams": ["Arts", "Science", "Commerce", "Law"],
        "top_recruiters": ["TCS", "Infosys", "Genpact", "Wipro"],
        "min_12th_marks": 60,
        "website": "caluniv.ac.in",
        "affiliation": "State University, Govt. of West Bengal",
        "founded": "1857",
        "description": "One of India's oldest universities; affiliates many Kolkata colleges.",
        "pros": ["Historic prestige", "Very low fees", "Strong science & arts"],
        "cons": ["Affiliated-college dependence", "Limited central placements"],
    },
    {
        "id": 18,
        "name": "IISc Bangalore",
        "location": "Bengaluru",
        "state": "Karnataka",
        "type": "govt",
        "nirf_rank": 2,
        "avg_package": "16.0",
        "placement_pct": 85,
        "rating": 4.9,
        "streams": ["Engineering", "Science", "Research", "Design"],
        "top_recruiters": ["Google", "Microsoft", "ISRO", "Qualcomm"],
        "min_12th_marks": 75,
        "website": "iisc.ac.in",
        "affiliation": "Ministry of Science & Technology, GoI",
        "founded": "1909",
        "description": "India's foremost institute for advanced scientific research.",
        "pros": [
            "World-class research",
            "Best for MS/PhD & science",
            "Excellent faculty",
        ],
        "cons": ["Research-focused, fewer UG seats", "Highly selective"],
    },
    {
        "id": 19,
        "name": "IIT Madras",
        "location": "Chennai",
        "state": "Tamil Nadu",
        "type": "govt",
        "nirf_rank": 1,
        "avg_package": "20.0",
        "placement_pct": 93,
        "rating": 4.9,
        "streams": ["Engineering", "Management", "Sciences", "Design"],
        "top_recruiters": ["Google", "Adobe", "Qualcomm", "Goldman Sachs"],
        "min_12th_marks": 75,
        "website": "iitm.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1959",
        "description": "India's #1 ranked IIT for several years; superb research & placements.",
        "pros": [
            "Top NIRF ranking",
            "Excellent CS & core placements",
            "Strong incubation/startups",
        ],
        "cons": ["Competitive, demanding", "Chennai heat (minor)"],
    },
    {
        "id": 20,
        "name": "IIT Kanpur",
        "location": "Kanpur",
        "state": "Uttar Pradesh",
        "type": "govt",
        "nirf_rank": 5,
        "avg_package": "19.0",
        "placement_pct": 92,
        "rating": 4.7,
        "streams": ["Engineering", "Sciences", "Management", "Design"],
        "top_recruiters": ["Microsoft", "Amazon", "Uber", "Goldman Sachs"],
        "min_12th_marks": 75,
        "website": "iitk.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1959",
        "description": "Pioneering IIT known for academics, aerospace and entrepreneurship.",
        "pros": [
            "Excellent academics & labs",
            "Strong alumni network",
            "Good placements",
        ],
        "cons": ["Demanding coursework", "Smaller town"],
    },
    {
        "id": 21,
        "name": "IIT Roorkee",
        "location": "Roorkee",
        "state": "Uttarakhand",
        "type": "govt",
        "nirf_rank": 7,
        "avg_package": "17.0",
        "placement_pct": 90,
        "rating": 4.6,
        "streams": ["Engineering", "Architecture", "Management", "Sciences"],
        "top_recruiters": ["Google", "Microsoft", "TCS", "L&T"],
        "min_12th_marks": 75,
        "website": "iitr.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1847",
        "description": "Asia's oldest technical institution; strong civil & engineering.",
        "pros": ["Historic legacy", "Excellent core engineering", "Good placements"],
        "cons": ["Smaller town (Roorkee)", "Cold winters"],
    },
    {
        "id": 22,
        "name": "IIT Guwahati",
        "location": "Guwahati",
        "state": "Assam",
        "type": "govt",
        "nirf_rank": 8,
        "avg_package": "15.0",
        "placement_pct": 88,
        "rating": 4.5,
        "streams": ["Engineering", "Sciences", "Design", "Management"],
        "top_recruiters": ["Microsoft", "Amazon", "TCS", "Adobe"],
        "min_12th_marks": 75,
        "website": "iitg.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1994",
        "description": "Scenic, fast-rising IIT in Northeast India.",
        "pros": [
            "Beautiful campus",
            "Growing placements & research",
            "Modern infrastructure",
        ],
        "cons": ["Remote location", "Fewer recruiters than older IITs"],
    },
    {
        "id": 23,
        "name": "IIT Hyderabad",
        "location": "Hyderabad",
        "state": "Telangana",
        "type": "govt",
        "nirf_rank": 11,
        "avg_package": "19.0",
        "placement_pct": 90,
        "rating": 4.5,
        "streams": ["Engineering", "Sciences", "Design"],
        "top_recruiters": ["Google", "Microsoft", "Apple", "Nvidia"],
        "min_12th_marks": 75,
        "website": "iith.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "2008",
        "description": "Young, research-intensive IIT with strong industry collaboration.",
        "pros": [
            "Excellent new-age curriculum",
            "Great CS placements",
            "Proximity to Hyderabad tech hub",
        ],
        "cons": ["Younger alumni network", "Still expanding"],
    },
    {
        "id": 24,
        "name": "IIT (BHU) Varanasi",
        "location": "Varanasi",
        "state": "Uttar Pradesh",
        "type": "govt",
        "nirf_rank": 13,
        "avg_package": "15.0",
        "placement_pct": 88,
        "rating": 4.4,
        "streams": ["Engineering", "Sciences", "Medical", "Management"],
        "top_recruiters": ["TCS", "Infosys", "Microsoft", "BHEL"],
        "min_12th_marks": 75,
        "website": "iitbhu.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1919",
        "description": "Historic IIT in Varanasi with growing placements.",
        "pros": ["Old campus & brand", "Good core & CS placements", "Low fees"],
        "cons": ["Administrative legacy issues", "Smaller than top IITs"],
    },
    {
        "id": 25,
        "name": "IIT Indore",
        "location": "Indore",
        "state": "Madhya Pradesh",
        "type": "govt",
        "nirf_rank": 16,
        "avg_package": "19.0",
        "placement_pct": 89,
        "rating": 4.5,
        "streams": ["Engineering", "Sciences", "Management"],
        "top_recruiters": ["Goldman Sachs", "Microsoft", "Amazon", "Uber"],
        "min_12th_marks": 75,
        "website": "iiti.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "2009",
        "description": "Fast-rising IIT with modern campus and strong research.",
        "pros": [
            "Excellent new campus",
            "Strong placements & research",
            "Discipline-focused",
        ],
        "cons": ["Younger alumni base", "Smaller cohort"],
    },
    {
        "id": 26,
        "name": "IIT Ropar",
        "location": "Rupnagar",
        "state": "Punjab",
        "type": "govt",
        "nirf_rank": 19,
        "avg_package": "15.0",
        "placement_pct": 86,
        "rating": 4.3,
        "streams": ["Engineering", "Sciences"],
        "top_recruiters": ["Adobe", "Microsoft", "Amazon", "Samsung"],
        "min_12th_marks": 75,
        "website": "iitrpr.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "2008",
        "description": "Compact, research-led IIT in Punjab.",
        "pros": ["Good faculty-to-student ratio", "Solid placements", "Modern labs"],
        "cons": ["Small campus", "Limited city exposure"],
    },
    {
        "id": 27,
        "name": "IIT Gandhinagar",
        "location": "Gandhinagar",
        "state": "Gujarat",
        "type": "govt",
        "nirf_rank": 18,
        "avg_package": "14.0",
        "placement_pct": 85,
        "rating": 4.3,
        "streams": ["Engineering", "Sciences", "Cognitive Science"],
        "top_recruiters": ["Microsoft", "TCS", "Reliance", "Infosys"],
        "min_12th_marks": 75,
        "website": "iitgn.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "2008",
        "description": "Liberal-arts-influenced IIT with innovative pedagogy.",
        "pros": [
            "Unique holistic curriculum",
            "Strong international links",
            "Good placements",
        ],
        "cons": ["Small, still growing", "Newer brand"],
    },
    {
        "id": 28,
        "name": "IIT Bhubaneswar",
        "location": "Bhubaneswar",
        "state": "Odisha",
        "type": "govt",
        "nirf_rank": 23,
        "avg_package": "12.0",
        "placement_pct": 82,
        "rating": 4.1,
        "streams": ["Engineering", "Sciences", "Architecture"],
        "top_recruiters": ["TCS", "Wipro", "Capgemini", "Infosys"],
        "min_12th_marks": 75,
        "website": "iitbbs.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "2008",
        "description": "Young IIT in Odisha with developing infrastructure.",
        "pros": ["Good faculty", "Growing placements", "Government-funded"],
        "cons": ["Under-construction campus", "Smaller recruiter pool"],
    },
    {
        "id": 29,
        "name": "IIT Patna",
        "location": "Patna",
        "state": "Bihar",
        "type": "govt",
        "nirf_rank": 21,
        "avg_package": "14.0",
        "placement_pct": 84,
        "rating": 4.2,
        "streams": ["Engineering", "Sciences", "Management"],
        "top_recruiters": ["Amazon", "Adobe", "Microsoft", "Samsung"],
        "min_12th_marks": 75,
        "website": "iitp.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "2008",
        "description": "Emerging IIT with improving placements.",
        "pros": ["Low fees, good academics", "Rising CS placements", "Modern campus"],
        "cons": ["Young institution", "Limited legacy network"],
    },
    {
        "id": 30,
        "name": "IIT Jodhpur",
        "location": "Jodhpur",
        "state": "Rajasthan",
        "type": "govt",
        "nirf_rank": 22,
        "avg_package": "13.0",
        "placement_pct": 83,
        "rating": 4.2,
        "streams": ["Engineering", "Sciences", "Management"],
        "top_recruiters": ["TCS", "Infosys", "Microsoft", "L&T"],
        "min_12th_marks": 75,
        "website": "iitj.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "2008",
        "description": "New-generation IIT in Rajasthan.",
        "pros": ["Modern interdisciplinary focus", "Good placements", "New campus"],
        "cons": ["Younger brand", "Small cohort"],
    },
    {
        "id": 31,
        "name": "IIT (ISM) Dhanbad",
        "location": "Dhanbad",
        "state": "Jharkhand",
        "type": "govt",
        "nirf_rank": 17,
        "avg_package": "13.0",
        "placement_pct": 85,
        "rating": 4.2,
        "streams": ["Engineering", "Sciences", "Management"],
        "top_recruiters": ["Coal India", "TCS", "L&T", "ONGC"],
        "min_12th_marks": 75,
        "website": "iitism.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1926",
        "description": "Legacy mining institute, now a top IIT with broad branches.",
        "pros": [
            "Strong earth-sciences & mining",
            "Good core placements",
            "Old institutional trust",
        ],
        "cons": ["Specialised reputation", "Smaller town"],
    },
    {
        "id": 32,
        "name": "NIT Surathkal",
        "location": "Mangaluru",
        "state": "Karnataka",
        "type": "govt",
        "nirf_rank": 12,
        "avg_package": "12.0",
        "placement_pct": 90,
        "rating": 4.5,
        "streams": ["Engineering", "Management", "Sciences"],
        "top_recruiters": ["Microsoft", "Adobe", "Qualcomm", "Samsung"],
        "min_12th_marks": 75,
        "website": "nitk.edu.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1960",
        "description": "Top NIT in Karnataka with beachside campus.",
        "pros": ["Excellent placements", "Beautiful campus near sea", "Strong alumni"],
        "cons": ["Highly competitive", "Large batches"],
    },
    {
        "id": 33,
        "name": "NIT Warangal",
        "location": "Warangal",
        "state": "Telangana",
        "type": "govt",
        "nirf_rank": 24,
        "avg_package": "12.0",
        "placement_pct": 89,
        "rating": 4.4,
        "streams": ["Engineering", "Management", "Sciences"],
        "top_recruiters": ["Microsoft", "Amazon", "TCS", "Qualcomm"],
        "min_12th_marks": 75,
        "website": "nitw.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1959",
        "description": "Among the oldest & best NITs in South India.",
        "pros": ["Strong brand & placements", "Good infrastructure", "Active fests"],
        "cons": ["Competitive entry", "Big batches"],
    },
    {
        "id": 34,
        "name": "NIT Rourkela",
        "location": "Rourkela",
        "state": "Odisha",
        "type": "govt",
        "nirf_rank": 15,
        "avg_package": "11.0",
        "placement_pct": 88,
        "rating": 4.3,
        "streams": ["Engineering", "Sciences", "Management"],
        "top_recruiters": ["TCS", "Infosys", "Microsoft", "L&T"],
        "min_12th_marks": 75,
        "website": "nitrkl.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1961",
        "description": "Large, well-ranked NIT in Odisha.",
        "pros": ["Excellent campus & labs", "Strong placements", "Research-active"],
        "cons": ["Remote location", "Large cohort"],
    },
    {
        "id": 35,
        "name": "NIT Calicut",
        "location": "Kozhikode",
        "state": "Kerala",
        "type": "govt",
        "nirf_rank": 25,
        "avg_package": "10.0",
        "placement_pct": 86,
        "rating": 4.2,
        "streams": ["Engineering", "Architecture", "Management", "Sciences"],
        "top_recruiters": ["TCS", "Infosys", "Microsoft", "BYJU'S"],
        "min_12th_marks": 75,
        "website": "nitc.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1961",
        "description": "Leading NIT in Kerala with solid academics.",
        "pros": ["Good placements & faculty", "Scenic campus", "Strong CS/EC"],
        "cons": [
            "Remote (Kozhikode outskirts)",
            "Smaller recruiter pool than top NITs",
        ],
    },
    {
        "id": 36,
        "name": "NIT Jaipur",
        "location": "Jaipur",
        "state": "Rajasthan",
        "type": "govt",
        "nirf_rank": 26,
        "avg_package": "9.0",
        "placement_pct": 84,
        "rating": 4.1,
        "streams": ["Engineering", "Architecture", "Management"],
        "top_recruiters": ["TCS", "Infosys", "Capgemini", "Wipro"],
        "min_12th_marks": 75,
        "website": "mnit.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1963",
        "description": "Reputed NIT in Rajasthan's capital.",
        "pros": ["Good placements", "Jaipur location", "Modern campus"],
        "cons": ["Growing but competitive", "Large batches"],
    },
    {
        "id": 37,
        "name": "NIT Nagpur",
        "location": "Nagpur",
        "state": "Maharashtra",
        "type": "govt",
        "nirf_rank": 27,
        "avg_package": "9.0",
        "placement_pct": 83,
        "rating": 4.1,
        "streams": ["Engineering", "Architecture", "Management"],
        "top_recruiters": ["TCS", "Infosys", "L&T", "Wipro"],
        "min_12th_marks": 75,
        "website": "vnit.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1960",
        "description": "Established NIT in Maharashtra.",
        "pros": [
            "Strong core & IT placements",
            "Good alumni",
            "Central India location",
        ],
        "cons": ["Administrative slowness", "Big batches"],
    },
    {
        "id": 38,
        "name": "SVNIT Surat",
        "location": "Surat",
        "state": "Gujarat",
        "type": "govt",
        "nirf_rank": 28,
        "avg_package": "8.5",
        "placement_pct": 82,
        "rating": 4.0,
        "streams": ["Engineering", "Architecture"],
        "top_recruiters": ["TCS", "Infosys", "L&T", "Reliance"],
        "min_12th_marks": 75,
        "website": "svnit.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1961",
        "description": "NIT in Gujarat with decent placements.",
        "pros": ["Good industry links (Surat)", "Low fees", "Solid academics"],
        "cons": ["Smaller brand than top NITs", "Limited high-end packages"],
    },
    {
        "id": 39,
        "name": "MNNIT Allahabad",
        "location": "Prayagraj",
        "state": "Uttar Pradesh",
        "type": "govt",
        "nirf_rank": 29,
        "avg_package": "9.0",
        "placement_pct": 85,
        "rating": 4.1,
        "streams": ["Engineering", "Management", "Sciences"],
        "top_recruiters": ["Microsoft", "Adobe", "TCS", "Amazon"],
        "min_12th_marks": 75,
        "website": "mnnit.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1961",
        "description": "Historic NIT in Prayagraj, strong in CS.",
        "pros": ["Excellent CS placements", "Low fees", "Good alumni"],
        "cons": ["Tier-2 city", "Large batches"],
    },
    {
        "id": 40,
        "name": "MANIT Bhopal",
        "location": "Bhopal",
        "state": "Madhya Pradesh",
        "type": "govt",
        "nirf_rank": 30,
        "avg_package": "8.5",
        "placement_pct": 80,
        "rating": 4.0,
        "streams": ["Engineering", "Architecture", "Management"],
        "top_recruiters": ["TCS", "Wipro", "Infosys", "L&T"],
        "min_12th_marks": 75,
        "website": "manit.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1960",
        "description": "NIT in Madhya Pradesh's capital.",
        "pros": ["Decent placements", "Central location", "Low fees"],
        "cons": ["Infrastructure gaps", "Competitive entry"],
    },
    {
        "id": 41,
        "name": "NIT Kurukshetra",
        "location": "Kurukshetra",
        "state": "Haryana",
        "type": "govt",
        "nirf_rank": 31,
        "avg_package": "9.0",
        "placement_pct": 82,
        "rating": 4.0,
        "streams": ["Engineering", "Architecture", "Management"],
        "top_recruiters": ["TCS", "Infosys", "L&T", "Wipro"],
        "min_12th_marks": 75,
        "website": "nitkkr.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1963",
        "description": "Well-known NIT in Haryana.",
        "pros": ["Good placements", "Proximity to Delhi NCR", "Low fees"],
        "cons": ["Large batches", "Tier-2 city"],
    },
    {
        "id": 42,
        "name": "NIT Jamshedpur",
        "location": "Jamshedpur",
        "state": "Jharkhand",
        "type": "govt",
        "nirf_rank": 32,
        "avg_package": "8.0",
        "placement_pct": 81,
        "rating": 4.0,
        "streams": ["Engineering", "Management"],
        "top_recruiters": ["TCS", "Infosys", "Tata Steel", "Wipro"],
        "min_12th_marks": 75,
        "website": "nitjsr.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1960",
        "description": "NIT in Jharkhand's industrial city.",
        "pros": ["Industry proximity (Jamshedpur)", "Good core placements", "Low fees"],
        "cons": ["Smaller campus", "Tier-2 city"],
    },
    {
        "id": 43,
        "name": "NIT Silchar",
        "location": "Silchar",
        "state": "Assam",
        "type": "govt",
        "nirf_rank": 33,
        "avg_package": "7.5",
        "placement_pct": 78,
        "rating": 3.9,
        "streams": ["Engineering", "Management"],
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Capgemini"],
        "min_12th_marks": 75,
        "website": "nits.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1967",
        "description": "NIT serving Northeast India.",
        "pros": [
            "Government-funded, low fees",
            "Growing placements",
            "Regional importance",
        ],
        "cons": ["Remote location", "Smaller recruiter pool"],
    },
    {
        "id": 44,
        "name": "IIIT Hyderabad",
        "location": "Hyderabad",
        "state": "Telangana",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "24.0",
        "placement_pct": 92,
        "rating": 4.6,
        "streams": ["CSE", "ECE", "Research"],
        "top_recruiters": ["Google", "Microsoft", "Amazon", "Adobe"],
        "min_12th_marks": 75,
        "website": "iiit.ac.in",
        "affiliation": "Deemed University (Public-Private Partnership)",
        "founded": "1998",
        "description": "Elite research-focused institute, among India's best for CS.",
        "pros": [
            "Outstanding CS research & placements",
            "Strong industry collaboration",
            "Excellent faculty",
        ],
        "cons": ["High fees for private model", "Extremely competitive"],
    },
    {
        "id": 45,
        "name": "IIIT Delhi",
        "location": "New Delhi",
        "state": "Delhi",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "16.0",
        "placement_pct": 88,
        "rating": 4.3,
        "streams": ["CSE", "ECE", "Research"],
        "top_recruiters": ["Adobe", "Microsoft", "Amazon", "Samsung"],
        "min_12th_marks": 75,
        "website": "iiitd.ac.in",
        "affiliation": "State University, Govt. of NCT Delhi",
        "founded": "2008",
        "description": "Research-intensive state university strong in CS/ECE.",
        "pros": [
            "Great CS placements & research",
            "Delhi location",
            "Modern curriculum",
        ],
        "cons": ["Demanding coursework", "Smaller than IITs"],
    },
    {
        "id": 46,
        "name": "DTU Delhi",
        "location": "New Delhi",
        "state": "Delhi",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "12.0",
        "placement_pct": 85,
        "rating": 4.2,
        "streams": ["Engineering", "Management", "Sciences"],
        "top_recruiters": ["Microsoft", "Amazon", "TCS", "Adobe"],
        "min_12th_marks": 70,
        "website": "dtu.ac.in",
        "affiliation": "State University, Govt. of NCT Delhi",
        "founded": "1941",
        "description": "Historic technical university in Delhi with strong placements.",
        "pros": [
            "Excellent Delhi location & alumni",
            "Good core & IT placements",
            "Low fees",
        ],
        "cons": ["Large batches", "Some aging infrastructure"],
    },
    {
        "id": 47,
        "name": "NSUT Delhi",
        "location": "New Delhi",
        "state": "Delhi",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "13.0",
        "placement_pct": 84,
        "rating": 4.2,
        "streams": ["Engineering", "Management"],
        "top_recruiters": ["Microsoft", "Amazon", "Adobe", "Samsung"],
        "min_12th_marks": 70,
        "website": "nsut.ac.in",
        "affiliation": "State University, Govt. of NCT Delhi",
        "founded": "1983",
        "description": "Top Delhi state university with great tech placements.",
        "pros": ["Strong CS/IT placements", "Delhi network", "Low fees"],
        "cons": ["Competitive entry", "Growing campus"],
    },
    {
        "id": 48,
        "name": "COEP Pune",
        "location": "Pune",
        "state": "Maharashtra",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "10.0",
        "placement_pct": 82,
        "rating": 4.1,
        "streams": ["Engineering", "Architecture"],
        "top_recruiters": ["TCS", "Infosys", "L&T", "Bosch"],
        "min_12th_marks": 70,
        "website": "coep.ac.in",
        "affiliation": "Autonomous, affiliated to Savitribai Phule Pune University",
        "founded": "1854",
        "description": "Maharashtra's premier government engineering college.",
        "pros": [
            "Historic brand & alumni",
            "Excellent Pune location",
            "Strong placements",
        ],
        "cons": ["Affiliation constraints", "Highly competitive"],
    },
    {
        "id": 49,
        "name": "PSG College of Technology",
        "location": "Coimbatore",
        "state": "Tamil Nadu",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "6.0",
        "placement_pct": 80,
        "rating": 4.0,
        "streams": ["Engineering", "Management"],
        "top_recruiters": ["TCS", "Infosys", "Zoho", "Wipro"],
        "min_12th_marks": 65,
        "website": "psgtech.edu.in",
        "affiliation": "Autonomous, affiliated to Anna University",
        "founded": "1951",
        "description": "Top private-aided engineering college in Tamil Nadu.",
        "pros": ["Excellent placements", "Strong industry ties", "Reputed brand"],
        "cons": ["Strict discipline", "High cutoff"],
    },
    {
        "id": 50,
        "name": "Thapar Institute",
        "location": "Patiala",
        "state": "Punjab",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "8.0",
        "placement_pct": 83,
        "rating": 4.1,
        "streams": ["Engineering", "Management", "Sciences"],
        "top_recruiters": ["Microsoft", "Amazon", "TCS", "L&T"],
        "min_12th_marks": 70,
        "website": "thapar.edu",
        "affiliation": "Deemed University (Private)",
        "founded": "1956",
        "description": "Long-established private institute in Punjab.",
        "pros": ["Good placements & alumni", "Modern campus", "Strong academics"],
        "cons": ["High fees", "Competitive for top branches"],
    },
    {
        "id": 51,
        "name": "BIT Mesra",
        "location": "Ranchi",
        "state": "Jharkhand",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "7.0",
        "placement_pct": 80,
        "rating": 4.0,
        "streams": ["Engineering", "Management", "Pharmacy"],
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Cognizant"],
        "min_12th_marks": 65,
        "website": "bitmesra.ac.in",
        "affiliation": "Deemed University (Private)",
        "founded": "1955",
        "description": "Reputed private deemed university in Ranchi.",
        "pros": ["Good placements & alumni", "Established brand", "Multiple campuses"],
        "cons": ["High fees", "Tier-2 city (Ranchi)"],
    },
    {
        "id": 52,
        "name": "Lovely Professional University",
        "location": "Phagwara",
        "state": "Punjab",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "5.0",
        "placement_pct": 75,
        "rating": 3.8,
        "streams": ["Engineering", "Management", "Pharmacy", "Law"],
        "top_recruiters": ["Cognizant", "Capgemini", "TCS", "Wipro"],
        "min_12th_marks": 55,
        "website": "lpu.in",
        "affiliation": "Private University (Punjab)",
        "founded": "2005",
        "description": "Very large private university with massive placement drives.",
        "pros": ["Huge placement volume", "Modern infrastructure", "Diverse programs"],
        "cons": ["High fees", "Variable branch quality"],
    },
    {
        "id": 53,
        "name": "Amity University",
        "location": "Noida",
        "state": "Uttar Pradesh",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "4.5",
        "placement_pct": 70,
        "rating": 3.7,
        "streams": ["Engineering", "Management", "Law", "Medical"],
        "top_recruiters": ["TCS", "Wipro", "HCL", "Infosys"],
        "min_12th_marks": 55,
        "website": "amity.edu",
        "affiliation": "Private University",
        "founded": "2005",
        "description": "Large private university with pan-India campuses.",
        "pros": [
            "Good infrastructure",
            "Decent placements for top branches",
            "Industry exposure",
        ],
        "cons": ["High fees", "Variable academic rigour"],
    },
    {
        "id": 54,
        "name": "Ashoka University",
        "location": "Sonipat",
        "state": "Haryana",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "8.0",
        "placement_pct": 70,
        "rating": 4.3,
        "streams": ["Liberal Arts", "Social Sciences", "Sciences"],
        "top_recruiters": ["Consulting", "NGOs", "Startups", "Academia"],
        "min_12th_marks": 60,
        "website": "ashoka.edu.in",
        "affiliation": "Private University (Haryana)",
        "founded": "2014",
        "description": "India's leading liberal-arts university.",
        "pros": [
            "Excellent liberal-arts education",
            "Great faculty & exposure",
            "Strong peer group",
        ],
        "cons": ["Very high fees", "Limited engineering/tech focus"],
    },
    {
        "id": 55,
        "name": "Shiv Nadar University",
        "location": "Greater Noida",
        "state": "Uttar Pradesh",
        "type": "private",
        "nirf_rank": None,
        "avg_package": "7.0",
        "placement_pct": 80,
        "rating": 4.2,
        "streams": ["Engineering", "Management", "Natural Sciences"],
        "top_recruiters": ["Microsoft", "Cognizant", "TCS", "Zoho"],
        "min_12th_marks": 65,
        "website": "snu.edu.in",
        "affiliation": "Private University (Uttar Pradesh)",
        "founded": "2011",
        "description": "Research-oriented private university near Delhi NCR.",
        "pros": [
            "Good faculty & infrastructure",
            "Growing placements",
            "Multidisciplinary",
        ],
        "cons": ["Young institution", "High fees"],
    },
    {
        "id": 56,
        "name": "IIM Ahmedabad",
        "location": "Ahmedabad",
        "state": "Gujarat",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "33.0",
        "placement_pct": 100,
        "rating": 4.9,
        "streams": ["MBA", "PGP", "Executive"],
        "top_recruiters": ["McKinsey", "BCG", "Goldman Sachs", "Amazon"],
        "min_12th_marks": 60,
        "website": "iima.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1961",
        "description": "India's top business school with global repute.",
        "pros": [
            "Best B-school brand in India",
            "Exceptional placements",
            "World-class faculty",
        ],
        "cons": ["Extremely competitive", "Very high fees"],
    },
    {
        "id": 57,
        "name": "IIM Bangalore",
        "location": "Bengaluru",
        "state": "Karnataka",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "32.0",
        "placement_pct": 100,
        "rating": 4.9,
        "streams": ["MBA", "PGP", "Executive"],
        "top_recruiters": ["McKinsey", "BCG", "Amazon", "Microsoft"],
        "min_12th_marks": 60,
        "website": "iimb.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1973",
        "description": "Elite B-school known for finance, consulting & research.",
        "pros": ["Top placements & alumni", "Bengaluru location", "Excellent faculty"],
        "cons": ["High fees", "Highly competitive"],
    },
    {
        "id": 58,
        "name": "IIM Calcutta",
        "location": "Kolkata",
        "state": "West Bengal",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "31.0",
        "placement_pct": 100,
        "rating": 4.8,
        "streams": ["MBA", "PGP", "Executive"],
        "top_recruiters": ["McKinsey", "BCG", "JP Morgan", "Amazon"],
        "min_12th_marks": 60,
        "website": "iimcal.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1961",
        "description": "India's first IIM; strong in finance & analytics.",
        "pros": ["Pioneer IIM brand", "Great finance placements", "Strong alumni"],
        "cons": ["High fees", "Competitive"],
    },
    {
        "id": 59,
        "name": "IIM Lucknow",
        "location": "Lucknow",
        "state": "Uttar Pradesh",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "28.0",
        "placement_pct": 99,
        "rating": 4.7,
        "streams": ["MBA", "PGP"],
        "top_recruiters": ["Deloitte", "Amazon", "BCG", "HUL"],
        "min_12th_marks": 60,
        "website": "iiml.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1984",
        "description": "Top-tier IIM with strong general-management placements.",
        "pros": ["Excellent placements", "Strong brand", "Good campus"],
        "cons": ["High fees", "Competitive"],
    },
    {
        "id": 60,
        "name": "IIM Indore",
        "location": "Indore",
        "state": "Madhya Pradesh",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "25.0",
        "placement_pct": 99,
        "rating": 4.7,
        "streams": ["MBA", "PGP", "IPM"],
        "top_recruiters": ["McKinsey", "BCG", "P&G", "Amazon"],
        "min_12th_marks": 60,
        "website": "iimidr.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1996",
        "description": "Fast-rising IIM with large integrated programs.",
        "pros": ["Strong placements & brand", "Modern campus", "IPM program"],
        "cons": ["High fees", "Competitive"],
    },
    {
        "id": 61,
        "name": "IIM Kozhikode",
        "location": "Kozhikode",
        "state": "Kerala",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "26.0",
        "placement_pct": 98,
        "rating": 4.6,
        "streams": ["MBA", "PGP"],
        "top_recruiters": ["McKinsey", "BCG", "HUL", "Amazon"],
        "min_12th_marks": 60,
        "website": "iimk.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "1996",
        "description": "Top IIM known for diverse, inclusive cohorts.",
        "pros": ["Good placements & culture", "Scenic campus", "Strong brand"],
        "cons": ["High fees", "Competitive"],
    },
    {
        "id": 62,
        "name": "FMS Delhi",
        "location": "New Delhi",
        "state": "Delhi",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "34.0",
        "placement_pct": 98,
        "rating": 4.6,
        "streams": ["MBA", "Executive"],
        "top_recruiters": ["McKinsey", "BCG", "HUL", "Amazon"],
        "min_12th_marks": 60,
        "website": "fms.edu",
        "affiliation": "Constituent of University of Delhi",
        "founded": "1954",
        "description": "Top public B-school with unbeatable ROI.",
        "pros": [
            "Extremely low fees, high ROI",
            "Excellent placements",
            "Delhi University brand",
        ],
        "cons": ["No hostel for all", "Highly competitive"],
    },
    {
        "id": 63,
        "name": "AIIMS Delhi",
        "location": "New Delhi",
        "state": "Delhi",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "12.0",
        "placement_pct": 95,
        "rating": 4.9,
        "streams": ["MBBS", "MD", "Research"],
        "top_recruiters": ["AIIMS", "PGI", "Apollo", "Fortis"],
        "min_12th_marks": 60,
        "website": "aiims.edu",
        "affiliation": "Ministry of Health & Family Welfare, GoI (Institute of National Importance)",
        "founded": "1956",
        "description": "India's premier medical institute and hospital.",
        "pros": [
            "Top medical education & research",
            "Huge clinical exposure",
            "National brand",
        ],
        "cons": ["Extremely competitive (NEET)", "Demanding training"],
    },
    {
        "id": 64,
        "name": "AIIMS Bhubaneswar",
        "location": "Bhubaneswar",
        "state": "Odisha",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "11.0",
        "placement_pct": 90,
        "rating": 4.5,
        "streams": ["MBBS", "MD"],
        "top_recruiters": ["AIIMS", "Govt Hospitals", "Apollo"],
        "min_12th_marks": 60,
        "website": "aiimsbhubaneswar.edu.in",
        "affiliation": "Ministry of Health & Family Welfare, GoI (Institute of National Importance)",
        "founded": "2012",
        "description": "New-gen AIIMS in Odisha with growing reputation.",
        "pros": ["Government-funded, modern", "Good clinical training", "Low fees"],
        "cons": ["Newer institution", "Still building research base"],
    },
    {
        "id": 65,
        "name": "AIIMS Jodhpur",
        "location": "Jodhpur",
        "state": "Rajasthan",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "11.0",
        "placement_pct": 88,
        "rating": 4.4,
        "streams": ["MBBS", "MD"],
        "top_recruiters": ["AIIMS", "Govt Hospitals"],
        "min_12th_marks": 60,
        "website": "aiimsjodhpur.edu.in",
        "affiliation": "Ministry of Health & Family Welfare, GoI (Institute of National Importance)",
        "founded": "2012",
        "description": "New-gen AIIMS in Rajasthan.",
        "pros": ["Modern infrastructure", "Low fees, government", "Good training"],
        "cons": ["Young institution", "Limited legacy"],
    },
    {
        "id": 66,
        "name": "AIIMS Bhopal",
        "location": "Bhopal",
        "state": "Madhya Pradesh",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "11.0",
        "placement_pct": 88,
        "rating": 4.4,
        "streams": ["MBBS", "MD"],
        "top_recruiters": ["AIIMS", "Govt Hospitals"],
        "min_12th_marks": 60,
        "website": "aiimsbhopal.edu.in",
        "affiliation": "Ministry of Health & Family Welfare, GoI (Institute of National Importance)",
        "founded": "2012",
        "description": "New-gen AIIMS in Madhya Pradesh.",
        "pros": ["Government-funded, modern", "Good clinical exposure", "Low fees"],
        "cons": ["Newer", "Still expanding"],
    },
    {
        "id": 67,
        "name": "IISER Pune",
        "location": "Pune",
        "state": "Maharashtra",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "9.0",
        "placement_pct": 80,
        "rating": 4.4,
        "streams": ["Science", "Research"],
        "top_recruiters": ["Research Labs", "PhD Programs", "Academia"],
        "min_12th_marks": 75,
        "website": "iiserpune.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "2006",
        "description": "Top institute for basic sciences & research.",
        "pros": [
            "World-class science research",
            "Low fees, INI status",
            "Great for PhD pathways",
        ],
        "cons": ["Research-focused, fewer UG jobs", "Highly selective"],
    },
    {
        "id": 68,
        "name": "IISER Kolkata",
        "location": "Kolkata",
        "state": "West Bengal",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "9.0",
        "placement_pct": 78,
        "rating": 4.3,
        "streams": ["Science", "Research"],
        "top_recruiters": ["Research Labs", "Academia"],
        "min_12th_marks": 75,
        "website": "iiserkol.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "2006",
        "description": "Leading IISER for integrated science education.",
        "pros": ["Strong basic-science research", "Low fees", "Good academic culture"],
        "cons": ["Few direct UG placements", "Research-track oriented"],
    },
    {
        "id": 69,
        "name": "IISER Bhopal",
        "location": "Bhopal",
        "state": "Madhya Pradesh",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "9.0",
        "placement_pct": 78,
        "rating": 4.3,
        "streams": ["Science", "Engineering", "Research"],
        "top_recruiters": ["Research Labs", "Academia"],
        "min_12th_marks": 75,
        "website": "iiserb.ac.in",
        "affiliation": "Ministry of Education, GoI (Institute of National Importance)",
        "founded": "2008",
        "description": "Multidisciplinary IISER with engineering-sciences.",
        "pros": ["Broad science & engineering-science", "Low fees", "Modern campus"],
        "cons": ["Younger", "Research-focused"],
    },
    {
        "id": 70,
        "name": "NLSIU Bangalore",
        "location": "Bengaluru",
        "state": "Karnataka",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "12.0",
        "placement_pct": 95,
        "rating": 4.8,
        "streams": ["Law", "LLM", "Research"],
        "top_recruiters": ["Top Law Firms", "Judiciary", "Corporate"],
        "min_12th_marks": 60,
        "website": "nlsiu.edu.in",
        "affiliation": "Public University, Govt. of Karnataka",
        "founded": "1987",
        "description": "India's top National Law School.",
        "pros": [
            "Best law school in India",
            "Excellent placements (law firms)",
            "Strong alumni",
        ],
        "cons": ["Extremely competitive (CLAT)", "Higher fees vs public"],
    },
    {
        "id": 71,
        "name": "NID Ahmedabad",
        "location": "Ahmedabad",
        "state": "Gujarat",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "8.0",
        "placement_pct": 90,
        "rating": 4.7,
        "streams": ["Design", "MDes"],
        "top_recruiters": ["Design Studios", "Microsoft", "Tata"],
        "min_12th_marks": 60,
        "website": "nid.edu",
        "affiliation": "Institute of National Importance, Min. of Commerce & Industry, GoI",
        "founded": "1961",
        "description": "India's premier design institute.",
        "pros": ["Top design education", "Excellent industry ties", "National brand"],
        "cons": ["Very competitive", "Limited seats"],
    },
    {
        "id": 72,
        "name": "Presidency University Kolkata",
        "location": "Kolkata",
        "state": "West Bengal",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "5.0",
        "placement_pct": 75,
        "rating": 4.3,
        "streams": ["Science", "Arts", "Social Sciences"],
        "top_recruiters": ["Academia", "Research", "Civil Services"],
        "min_12th_marks": 65,
        "website": "presiuniv.ac.in",
        "affiliation": "State University, Govt. of West Bengal",
        "founded": "1817",
        "description": "Historic elite college/university in Kolkata.",
        "pros": [
            "Prestigious academic legacy",
            "Low fees, strong faculty",
            "Great for sciences/humanities",
        ],
        "cons": ["Limited professional placements", "Highly rigorous"],
    },
    {
        "id": 73,
        "name": "ISI Kolkata",
        "location": "Kolkata",
        "state": "West Bengal",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "12.0",
        "placement_pct": 90,
        "rating": 4.6,
        "streams": ["Statistics", "Math", "Research"],
        "top_recruiters": ["Quant Firms", "Google", "Microsoft", "Banks"],
        "min_12th_marks": 75,
        "website": "isical.ac.in",
        "affiliation": "Ministry of Statistics & Programme Implementation, GoI (Institute of National Importance)",
        "founded": "1931",
        "description": "World-renowned institute for statistics & mathematics.",
        "pros": ["Elite for stats/maths", "Low fees, government", "Excellent research"],
        "cons": ["Very selective", "Niche, research-focused"],
    },
    {
        "id": 74,
        "name": "St. Stephen's College",
        "location": "New Delhi",
        "state": "Delhi",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "6.0",
        "placement_pct": 78,
        "rating": 4.4,
        "streams": ["Arts", "Science"],
        "top_recruiters": ["Civil Services", "Academia", "Corporate"],
        "min_12th_marks": 65,
        "website": "ststephens.edu",
        "affiliation": "Constituent College, University of Delhi (Christian Minority)",
        "founded": "1881",
        "description": "India's most prestigious liberal-arts college.",
        "pros": [
            "Top DU college brand",
            "Excellent humanities/science",
            "Strong alumni",
        ],
        "cons": ["Highly competitive", "Limited professional courses"],
    },
    {
        "id": 75,
        "name": "BIT Sindri",
        "location": "Dhanbad",
        "state": "Jharkhand",
        "type": "govt",
        "nirf_rank": None,
        "avg_package": "6.0",
        "placement_pct": 75,
        "rating": 4.0,
        "streams": ["Engineering"],
        "top_recruiters": ["TCS", "Coal India", "L&T", "Wipro"],
        "min_12th_marks": 65,
        "website": "bitsindri.ac.in",
        "affiliation": "State Govt. Engineering College, Jharkhand",
        "founded": "1949",
        "description": "Old, respected government engineering college in Jharkhand.",
        "pros": [
            "Low fees, government",
            "Good alumni in East India",
            "Solid core branches",
        ],
        "cons": ["Infrastructure needs upgrade", "Limited high-end placements"],
    },
]

# ---- reusable document / college templates for scholarships ----
_SCH_DOC_GOV = [
    "Aadhaar card",
    "Income certificate",
    "Previous year marksheet",
    "Admission proof / fee receipt",
    "Bank passbook (cancelled cheque)",
]
_SCH_DOC_MIN = [
    "Domicile certificate",
    "Minority community certificate",
    "Income certificate",
    "Aadhaar card",
    "Previous year marksheet",
    "Bank passbook",
]
_SCH_DOC_CASTE = [
    "Caste certificate",
    "Income certificate",
    "Aadhaar card",
    "Previous year marksheet",
    "Admission proof",
    "Bank passbook",
]
_SCH_DOC_PRIV = [
    "Statement of Purpose (SOP)",
    "Income certificate",
    "Previous year marksheet",
    "Recommendation letter",
    "Aadhaar card",
    "Bank passbook",
]

_SCH_TECH = [
    "Jadavpur University",
    "IIEST Shibpur",
    "NIT Durgapur",
    "NIT Trichy",
    "BITS Pilani",
    "VIT Vellore",
    "SRM Institute of Science & Technology",
    "Manipal Academy of Higher Education",
    "Amrita Vishwa Vidyapeetham",
    "IIT Kharagpur",
    "IIT Bombay",
    "IIT Delhi",
]
_SCH_SCI = [
    "Jadavpur University",
    "University of Calcutta",
    "IIEST Shibpur",
    "Jawaharlal Nehru University",
    "Banaras Hindu University",
    "Anna University",
    "IIT Kharagpur",
    "IIT Bombay",
    "IIT Delhi",
]
_SCH_WB = ["Jadavpur University", "University of Calcutta", "IIEST Shibpur"]
_SCH_RELIANCE = [
    "IIT Kharagpur",
    "IIT Bombay",
    "IIT Delhi",
    "Jadavpur University",
    "IIEST Shibpur",
    "NIT Durgapur",
    "NIT Trichy",
    "BITS Pilani",
    "VIT Vellore",
    "Manipal Academy of Higher Education",
    "SRM Institute of Science & Technology",
    "Anna University",
]
_SCH_TATA = [
    "Jadavpur University",
    "University of Calcutta",
    "Banaras Hindu University",
    "Jawaharlal Nehru University",
    "Anna University",
    "Delhi University",
    "IIT Bombay",
    "IIT Delhi",
]
_SCH_ONGC = [
    "IIT Kharagpur",
    "IIT Bombay",
    "IIT Delhi",
    "Jadavpur University",
    "IIEST Shibpur",
    "NIT Durgapur",
    "NIT Trichy",
    "BITS Pilani",
]
_SCH_JSW = [
    "IIT Kharagpur",
    "Jadavpur University",
    "NIT Durgapur",
    "IIEST Shibpur",
    "BITS Pilani",
    "VIT Vellore",
]

SEED_SCHOLARSHIPS = [
    # ---------------- CENTRAL GOVERNMENT ----------------
    {
        "id": 1,
        "name": "Prime Minister's Scholarship Scheme (PMSS)",
        "amount": "\u20b930,000 (boys) / \u20b936,000 (girls) per year (professional courses)",
        "eligibility": "Wards / widows of ex-servicemen, serving personnel and paramiliaries (CAPF / Assam Rifles); minimum 60% in previous exam",
        "deadline": "31 October",
        "category": "Government",
        "state": "Central",
        "documents": _SCH_DOC_GOV,
        "colleges": ["All"],
        "provider": "Kendriya Sainik Board, Ministry of Defence, GoI",
        "link": "https://ksb.gov.in",
        "description": "For wards of ex-servicemen / serving personnel; professional courses get the higher amount.",
    },
    {
        "id": 2,
        "name": "NSP - Central Sector Scheme of Scholarships (CSSS)",
        "amount": "\u20b912,000/year (1st\u20133rd yr) \u00b7 \u20b920,000 (4th yr, professional)",
        "eligibility": "Class 12 pass with ≥80% (state quota), family income below ₹8 lakh per annum",
        "deadline": "31 December",
        "category": "Government",
        "state": "Central",
        "documents": _SCH_DOC_GOV,
        "colleges": ["All"],
        "provider": "Department of Higher Education, Ministry of Education, GoI (via NSP)",
        "link": "https://scholarships.gov.in",
        "description": "For Class XII top-20% students continuing general or professional UG studies.",
    },
    {
        "id": 3,
        "name": "Post Matric Scholarship for SC",
        "amount": "Full tuition + maintenance allowance",
        "eligibility": "SC students with family income below ₹2.5 lakh per annum in a recognised institution",
        "deadline": "31 March",
        "category": "Government",
        "state": "Central",
        "documents": _SCH_DOC_CASTE,
        "colleges": ["All"],
        "provider": "Ministry of Social Justice & Empowerment, GoI (NSP)",
        "link": "https://scholarships.gov.in",
        "description": "Post-matric financial aid for Scheduled Caste students.",
    },
    {
        "id": 4,
        "name": "Post Matric Scholarship for OBC",
        "amount": "Maintenance allowance + course fees",
        "eligibility": "OBC students with family income below ₹1.5 lakh per annum",
        "deadline": "31 March",
        "category": "Government",
        "state": "Central",
        "documents": _SCH_DOC_CASTE,
        "colleges": ["All"],
        "provider": "Ministry of Social Justice & Empowerment, GoI (NSP)",
        "link": "https://scholarships.gov.in",
        "description": "Post-matric aid for OBC students from low-income families.",
    },
    {
        "id": 5,
        "name": "Pre & Post Matric Scholarship for Minorities (MOMA)",
        "amount": "Up to \u20b91,000/year (pre) / actual tuition + maintenance (post)",
        "eligibility": "Students from notified minority communities with family income below ₹2 lakh per annum",
        "deadline": "31 December",
        "category": "Government",
        "state": "Central",
        "documents": _SCH_DOC_MIN,
        "colleges": ["All"],
        "provider": "Ministry of Minority Affairs, GoI (NSP)",
        "link": "https://scholarships.gov.in",
        "description": "Pre & post-matric support for minority-community students.",
    },
    {
        "id": 6,
        "name": "INSPIRE Scholarship (INSPIRE-HELP)",
        "amount": "₹80,000/year (for 5 years)",
        "eligibility": "Top 1% in Class 12 board exams OR JEE Advanced qualified, pursuing basic & natural sciences",
        "deadline": "31 December",
        "category": "Government",
        "state": "Central",
        "documents": [
            "Class 12 marksheet",
            "JEE Advanced / board rank proof",
            "Aadhaar card",
            "Admission proof",
            "Bank passbook",
        ],
        "colleges": _SCH_SCI,
        "provider": "Department of Science & Technology, GoI",
        "link": "https://inspire.gov.in",
        "description": "For top learners in basic & natural sciences (BSc/MSc).",
    },
    {
        "id": 7,
        "name": "AICTE Pragati Scholarship (Girls)",
        "amount": "₹50,000/year (up to 4 years)",
        "eligibility": "Female students admitted to AICTE-approved technical institutions; family income below ₹8 lakh",
        "deadline": "30 November",
        "category": "Government",
        "state": "All India",
        "documents": [
            "Aadhaar card",
            "Income certificate",
            "Admission proof / fee receipt",
            "Previous year marksheet",
            "Bank passbook",
        ],
        "colleges": _SCH_TECH,
        "provider": "AICTE, Ministry of Education, GoI",
        "link": "https://www.aicte-india.org",
        "description": "For girls in AICTE-approved technical diploma/degree programs.",
    },
    {
        "id": 8,
        "name": "AICTE Saksham Scholarship (PwD)",
        "amount": "₹50,000/year (up to 4 years)",
        "eligibility": "Students with benchmark disability admitted to AICTE institutions; family income below ₹8 lakh",
        "deadline": "30 November",
        "category": "Government",
        "state": "All India",
        "documents": [
            "Disability certificate",
            "Income certificate",
            "Aadhaar card",
            "Admission proof",
            "Bank passbook",
        ],
        "colleges": _SCH_TECH,
        "provider": "AICTE, Ministry of Education, GoI",
        "link": "https://www.aicte-india.org",
        "description": "For PwD students in AICTE-approved technical programs.",
    },
    {
        "id": 9,
        "name": "UGC Ishan Uday Scholarship",
        "amount": "₹5,400 / ₹7,800 per month",
        "eligibility": "Students from the North Eastern states pursuing UG degrees in recognised institutions",
        "deadline": "31 December",
        "category": "Government",
        "state": "North East",
        "documents": [
            "Domicile certificate (NE state)",
            "Class 12 marksheet",
            "Income certificate",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "UGC, GoI",
        "link": "https://www.ugc.gov.in",
        "description": "For students from North-Eastern states pursuing UG studies.",
    },
    {
        "id": 10,
        "name": "Maulana Azad National Fellowship (MANF)",
        "amount": "₹25,000 / ₹28,000 per month",
        "eligibility": "Minority-community students pursuing M.Phil / PhD in recognised universities",
        "deadline": "31 December",
        "category": "Government",
        "state": "Central",
        "documents": [
            "Minority community certificate",
            "Income certificate",
            "Aadhaar card",
            "Post-graduate marksheet",
            "Research proposal",
            "Admission proof",
        ],
        "colleges": ["All"],
        "provider": "Ministry of Minority Affairs, GoI (UGC)",
        "link": "https://scholarships.gov.in",
        "description": "Fellowship for minority students pursuing MPhil/PhD.",
    },
    {
        "id": 11,
        "name": "National Fellowship for SC (RGF)",
        "amount": "₹25,000 / ₹28,000 per month",
        "eligibility": "SC students pursuing M.Phil / PhD in recognised universities",
        "deadline": "31 December",
        "category": "Government",
        "state": "Central",
        "documents": [
            "Caste certificate",
            "Income certificate",
            "Aadhaar card",
            "Post-graduate marksheet",
            "Admission proof",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "UGC, GoI",
        "link": "https://www.ugc.gov.in",
        "description": "Fellowship for Scheduled Caste scholars (MPhil/PhD).",
    },
    {
        "id": 12,
        "name": "Swami Vivekananda Single Girl Child Fellowship (SGC)",
        "amount": "₹36,200/year",
        "eligibility": "Single girl child pursuing post-graduation in recognised Indian universities",
        "deadline": "31 December",
        "category": "Government",
        "state": "Central",
        "documents": [
            "Birth certificate (single girl child)",
            "Previous year marksheet",
            "Income certificate",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "UGC, GoI",
        "link": "https://www.ugc.gov.in",
        "description": "For single girl children pursuing PG studies.",
    },
    {
        "id": 13,
        "name": "PM-YASASVI Central Sector Top Class Scheme",
        "amount": "₹90,000 (others) / ₹1.25 lakh (professional) per year + maintenance",
        "eligibility": "OBC/EBC/SC/DNT students in Top Class institutions; family income below ₹2.5 lakh",
        "deadline": "31 October",
        "category": "Government",
        "state": "Central",
        "documents": [
            "Caste / DNT certificate",
            "Income certificate",
            "Class 12 marksheet",
            "Admission proof",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "Ministry of Social Justice & Empowerment, GoI (NSP)",
        "link": "https://scholarships.gov.in",
        "description": "Top-class education support for OBC/SC/Denotified tribe students.",
    },
    {
        "id": 14,
        "name": "NEC Merit Scholarship",
        "amount": "₹20,000 - ₹30,000/year",
        "eligibility": "Students from North Eastern states with good academic record",
        "deadline": "31 December",
        "category": "Government",
        "state": "North East",
        "documents": [
            "Domicile certificate (NE state)",
            "Previous year marksheet",
            "Income certificate",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "North Eastern Council, Ministry of DoNER, GoI",
        "link": "https://necouncil.gov.in",
        "description": "Merit scholarship for students from North-Eastern states.",
    },
    {
        "id": 15,
        "name": "PM Special Scholarship Scheme for J&K (PMSSS)",
        "amount": "₹1 lakh (general) / ₹1.25 lakh (professional) per year + maintenance",
        "eligibility": "Students from Jammu & Kashmir / Ladakh studying outside the UT in recognised institutions",
        "deadline": "31 August",
        "category": "Government",
        "state": "Central",
        "documents": [
            "Domicile certificate (J&K/Ladakh)",
            "Class 12 marksheet",
            "Admission proof",
            "Income certificate",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "AICTE for J&K (Ministry of Education, GoI)",
        "link": "https://www.aicte-india.org",
        "description": "For J&K students to study in institutions outside the Union Territory.",
    },
    # ---------------- STATE GOVERNMENT ----------------
    {
        "id": 16,
        "name": "Aikyashree (West Bengal Minority Scholarship)",
        "amount": "₹1,100 - ₹6,600/year",
        "eligibility": "Minority-community students domiciled in West Bengal; family income below ₹2.5 lakh",
        "deadline": "31 January",
        "category": "State",
        "state": "West Bengal",
        "documents": _SCH_DOC_MIN,
        "colleges": ["All"],
        "provider": "Minority Affairs & Madrasah Education Dept., Govt. of West Bengal",
        "link": "https://wbmdfc.org",
        "description": "Pre/post-matric scholarships for West Bengal minorities.",
    },
    {
        "id": 17,
        "name": "Swami Vivekananda Merit-cum-Means (SVMCM), WB",
        "amount": "\u20b98,000 \u2013 \u20b910,000/month (UG) \u00b7 \u20b910,000 \u2013 \u20b912,000/month (PG)",
        "eligibility": "West Bengal domiciled UG/PG students with merit and family income below ₹2.5 lakh",
        "deadline": "31 January",
        "category": "State",
        "state": "West Bengal",
        "documents": [
            "Domicile certificate",
            "Income certificate",
            "Previous year marksheet",
            "Admission proof",
            "Bank passbook",
        ],
        "colleges": _SCH_WB,
        "provider": "Higher Education Dept., Govt. of West Bengal",
        "link": "https://svmmcm.wbhed.gov.in",
        "description": "Merit-cum-means scholarship for West Bengal UG/PG students.",
    },
    {
        "id": 18,
        "name": "Kanyashree (West Bengal)",
        "amount": "₹1,000 (K1 annual) / ₹25,000 (K2 one-time)",
        "eligibility": "Unmarried girls aged 13-19 enrolled in school/college; family income below ₹1.2 lakh (K2)",
        "deadline": "31 August",
        "category": "State",
        "state": "West Bengal",
        "documents": [
            "Birth certificate",
            "Income certificate",
            "Enrolment proof",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "Dept. of Women Development & Social Welfare, Govt. of West Bengal",
        "link": "https://www.kanyashree.gov.in",
        "description": "Annual incentive for girls continuing education.",
    },
    {
        "id": 19,
        "name": "Kerala State Merit Scholarship",
        "amount": "₹1,250 - ₹3,000/year",
        "eligibility": "Kerala-domiciled students with annual family income below ₹1 lakh and high marks",
        "deadline": "31 October",
        "category": "State",
        "state": "Kerala",
        "documents": [
            "Domicile certificate",
            "Income certificate",
            "Aadhaar card",
            "Previous year marksheet",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "Dept. of Collegiate Education, Govt. of Kerala",
        "link": "https://www.dcescholarship.kerala.gov.in",
        "description": "Merit scholarship for Kerala UG students.",
    },
    {
        "id": 20,
        "name": "Kerala Post Matric Scholarship (SC/OBC/General)",
        "amount": "Tuition + maintenance as per category",
        "eligibility": "Kerala-domiciled students from SC/OBC/General categories in recognised institutions",
        "deadline": "31 December",
        "category": "State",
        "state": "Kerala",
        "documents": _SCH_DOC_CASTE,
        "colleges": ["All"],
        "provider": "Social Justice / SC-ST-OBC Depts., Govt. of Kerala",
        "link": "https://www.dcescholarship.kerala.gov.in",
        "description": "Post-matric aid for Kerala students by category.",
    },
    {
        "id": 21,
        "name": "Tamil Nadu Government School to College Scholarship",
        "amount": "₹20,000 - ₹25,000/year",
        "eligibility": "Tamil Nadu government-school students securing high marks in Class 12 and pursuing UG",
        "deadline": "31 December",
        "category": "State",
        "state": "Tamil Nadu",
        "documents": [
            "Domicile certificate (TN)",
            "Class 12 marksheet (govt school)",
            "Income certificate",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "School Education Dept., Govt. of Tamil Nadu",
        "link": "https://www.tn.gov.in",
        "description": "For government-school students entering UG studies.",
    },
    {
        "id": 22,
        "name": "Karnataka Vidyasiri / SSP Post Matric",
        "amount": "₹1,500 - ₹3,500 (boarding) + course fees",
        "eligibility": "Karnataka-domiciled BPL / low-income students in recognised institutions",
        "deadline": "31 December",
        "category": "State",
        "state": "Karnataka",
        "documents": [
            "Domicile certificate (KA)",
            "Income / BPL certificate",
            "Caste certificate (if applicable)",
            "Previous year marksheet",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "Social Welfare Dept., Govt. of Karnataka",
        "link": "https://ssp.karnataka.gov.in",
        "description": "Post-matric hostel & scholarship for Karnataka students.",
    },
    {
        "id": 23,
        "name": "Maharashtra Rajarshi Shahu Maharaj EBC Scholarship",
        "amount": "Full tuition (capped) for EBC students",
        "eligibility": "Maharashtra-domiciled EBC students; family income below ₹8 lakh",
        "deadline": "31 December",
        "category": "State",
        "state": "Maharashtra",
        "documents": [
            "Domicile certificate (MH)",
            "Income (EBC) certificate",
            "Previous year marksheet",
            "Admission proof",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "Social Justice Dept., Govt. of Maharashtra",
        "link": "https://www.mahadbt.gov.in",
        "description": "For EBC students from Maharashtra.",
    },
    {
        "id": 24,
        "name": "Uttar Pradesh Scholarship (Pre/Post Matric)",
        "amount": "Tuition + maintenance as per category",
        "eligibility": "Uttar Pradesh-domiciled SC/ST/OBC/General students in recognised institutions",
        "deadline": "31 December",
        "category": "State",
        "state": "Uttar Pradesh",
        "documents": _SCH_DOC_CASTE,
        "colleges": ["All"],
        "provider": "Social Welfare Dept., Govt. of Uttar Pradesh",
        "link": "https://scholarship.up.gov.in",
        "description": "Pre/post-matric scholarships for UP students.",
    },
    {
        "id": 25,
        "name": "Bihar Scholarship (Post Matric)",
        "amount": "Tuition + maintenance as per category",
        "eligibility": "Bihar-domiciled SC/ST/OBC/BC/EBC students in recognised institutions",
        "deadline": "31 December",
        "category": "State",
        "state": "Bihar",
        "documents": _SCH_DOC_CASTE,
        "colleges": ["All"],
        "provider": "SC/ST/OBC Welfare Dept., Govt. of Bihar",
        "link": "https://pmsonline.bih.nic.in",
        "description": "Post-matric aid for Bihar students.",
    },
    {
        "id": 26,
        "name": "Gujarat Mukhyamantri Yuva Swavalamban (MYS) Yojana",
        "amount": "₹10,000 - ₹25,000/year",
        "eligibility": "Gujarat-domiciled students with high Class 12 marks; family income below ₹6 lakh",
        "deadline": "31 December",
        "category": "State",
        "state": "Gujarat",
        "documents": [
            "Domicile certificate (GJ)",
            "Class 12 marksheet",
            "Income certificate",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "Education Dept., Govt. of Gujarat",
        "link": "https://www.digitalgujarat.gov.in",
        "description": "For Gujarat students within family-income limits.",
    },
    {
        "id": 27,
        "name": "Rajasthan Post Matric Scholarship",
        "amount": "Tuition + maintenance as per category",
        "eligibility": "Rajasthan-domiciled SC/ST/OBC/SBC students in recognised institutions",
        "deadline": "31 December",
        "category": "State",
        "state": "Rajasthan",
        "documents": _SCH_DOC_CASTE,
        "colleges": ["All"],
        "provider": "Social Justice & Empowerment Dept., Govt. of Rajasthan",
        "link": "https://sje.rajasthan.gov.in",
        "description": "Post-matric aid for Rajasthan students.",
    },
    {
        "id": 28,
        "name": "Odisha Post Matric Scholarship (BOC)",
        "amount": "Tuition + maintenance as per category",
        "eligibility": "Odisha-domiciled SC/ST/OBC/SEBC students in recognised institutions",
        "deadline": "31 December",
        "category": "State",
        "state": "Odisha",
        "documents": _SCH_DOC_CASTE,
        "colleges": ["All"],
        "provider": "ST/SC Development Dept., Govt. of Odisha",
        "link": "https://scholarship.odisha.gov.in",
        "description": "Post-matric scholarship for Odisha students.",
    },
    # ---------------- PRIVATE / CORPORATE ----------------
    {
        "id": 29,
        "name": "Reliance Foundation Scholarship",
        "amount": "Up to ₹2,00,000/year",
        "eligibility": "First-year UG students in engineering / agriculture with strong academics; family income below ₹15 lakh",
        "deadline": "15 October",
        "category": "Private",
        "state": "All India",
        "documents": _SCH_DOC_PRIV,
        "colleges": _SCH_RELIANCE,
        "provider": "Reliance Foundation",
        "link": "https://www.reliancefoundation.org",
        "description": "Merit-cum-means for UG students in partner institutions.",
    },
    {
        "id": 30,
        "name": "Tata Trusts (Tata Scholars / JN Tata Endowment)",
        "amount": "Need-based, up to full tuition",
        "eligibility": "Meritorious students from economically weaker sections at partner institutions",
        "deadline": "30 September",
        "category": "Private",
        "state": "All India",
        "documents": _SCH_DOC_PRIV,
        "colleges": _SCH_TATA,
        "provider": "Tata Trusts",
        "link": "https://www.tatatrusts.org",
        "description": "Loan/grant scholarships for higher studies.",
    },
    {
        "id": 31,
        "name": "ONGC Scholarship",
        "amount": "₹48,000/year",
        "eligibility": "Students from SC/ST/OBC & General (EWS) in engineering, medical, MBA & masters; family income below ₹4.5 lakh",
        "deadline": "15 November",
        "category": "Private",
        "state": "All India",
        "documents": [
            "Caste / EWS certificate",
            "Income certificate",
            "Aadhaar card",
            "Previous year marksheet",
            "Admission proof",
            "Bank passbook",
        ],
        "colleges": _SCH_ONGC,
        "provider": "ONGC (CSR)",
        "link": "https://www.ongcindia.com",
        "description": "Merit scholarships for meritorious students (incl. SC/ST/OBC/PwD).",
    },
    {
        "id": 32,
        "name": "LIC Golden Jubilee Scholarship",
        "amount": "₹20,000/year",
        "eligibility": "Students studying beyond Class 12 with family income below ₹4 lakh",
        "deadline": "31 December",
        "category": "Private",
        "state": "All India",
        "documents": [
            "Income certificate",
            "Class 12 marksheet",
            "Admission proof",
            "Bank passbook",
        ],
        "colleges": ["All"],
        "provider": "LIC Golden Jubilee Foundation",
        "link": "https://www.licindia.in",
        "description": "For economically weaker students in 10th/12th/UG.",
    },
    {
        "id": 33,
        "name": "HDFC Bank Parivartan Scholarship",
        "amount": "Up to ₹75,000/year",
        "eligibility": "Need-based UG/PG students; family income below ₹3 lakh (rural) / ₹5 lakh (urban)",
        "deadline": "30 September",
        "category": "Private",
        "state": "All India",
        "documents": _SCH_DOC_PRIV,
        "colleges": ["All"],
        "provider": "HDFC Bank Parivartan",
        "link": "https://www.hdfcbank.com",
        "description": "Need-based scholarships for school & college students.",
    },
    {
        "id": 34,
        "name": "Axis Bank CSSI Scholarship",
        "amount": "₹25,000 - ₹50,000/year",
        "eligibility": "UG students with family income below ₹5 lakh",
        "deadline": "30 September",
        "category": "Private",
        "state": "All India",
        "documents": _SCH_DOC_PRIV,
        "colleges": ["All"],
        "provider": "Axis Bank Foundation",
        "link": "https://www.axisbankfoundation.org",
        "description": "For students from low-income households.",
    },
    {
        "id": 35,
        "name": "Aditya Birla Capital Scholarship",
        "amount": "₹12,000 - ₹60,000/year",
        "eligibility": "Students of Class 9-12 & UG with family income below ₹3.5 lakh",
        "deadline": "30 September",
        "category": "Private",
        "state": "All India",
        "documents": _SCH_DOC_PRIV,
        "colleges": ["All"],
        "provider": "Aditya Birla Capital",
        "link": "https://www.adityabirlacapital.com",
        "description": "For students from economically weaker sections.",
    },
    {
        "id": 36,
        "name": "Keep India Smiling (Colgate)",
        "amount": "₹10,000 - ₹30,000/year",
        "eligibility": "Need-based support for students of Class 9-12 & college",
        "deadline": "31 October",
        "category": "Private",
        "state": "All India",
        "documents": _SCH_DOC_PRIV,
        "colleges": ["All"],
        "provider": "Colgate-Palmolive (Keep India Smiling)",
        "link": "https://www.colgate.com",
        "description": "For sports, education & hygiene aspirants.",
    },
    {
        "id": 37,
        "name": "JSW Foundation Scholarship",
        "amount": "Up to ₹50,000/year",
        "eligibility": "Students of engineering / medical / management with financial need",
        "deadline": "30 November",
        "category": "Private",
        "state": "All India",
        "documents": _SCH_DOC_PRIV,
        "colleges": _SCH_JSW,
        "provider": "JSW Foundation",
        "link": "https://www.jsw.in",
        "description": "For meritorious students from JSW-operational districts.",
    },
    {
        "id": 38,
        "name": "Sahu Jain Scholarship",
        "amount": "₹10,000 - ₹50,000 (one-time)",
        "eligibility": "Meritorious students with financial need across all fields of study",
        "deadline": "31 December",
        "category": "Private",
        "state": "All India",
        "documents": _SCH_DOC_PRIV,
        "colleges": ["All"],
        "provider": "Sahu Jain Trust",
        "link": "https://www.sahujaintrust.org",
        "description": "Need-cum-merit scholarship for Indian students.",
    },
]


def seed_all():
    if not db_available():
        print("[learnify] db not configured; skipping seed.")
        return

    client = get_client()
    try:
        client.table("colleges").upsert(SEED_COLLEGES, on_conflict="name").execute()
        print(f"[learnify] seeded {len(SEED_COLLEGES)} colleges.")
    except Exception as e:
        print(f"[learnify] college seed error: {e}")

    try:
        client.table("scholarships").upsert(
            SEED_SCHOLARSHIPS, on_conflict="name"
        ).execute()
        print(f"[learnify] seeded {len(SEED_SCHOLARSHIPS)} scholarships.")
    except Exception as e:
        print(f"[learnify] scholarship seed error: {e}")


if __name__ == "__main__":
    seed_all()
