"""
Seed learning resources — curated courses, tutorials, and materials mapped to skills.
Run: python -m backend.database.seed_learning
"""

import json
from backend.database.client import get_client, db_available

RESOURCES = [
    {
        "title": "Python for Everybody",
        "description": "Learn Python basics through practical examples. Covers variables, loops, functions, and data structures.",
        "url": "https://www.coursera.org/specializations/python",
        "provider": "Coursera",
        "category": "COURSE",
        "difficulty": "BEGINNER",
        "duration_minutes": 600,
        "skill_name": "Python",
        "rating": 4.8,
        "enrollment_count": 2500000,
    },
    {
        "title": "Automate the Boring Stuff with Python",
        "description": "Practical Python programming for beginners. Web scraping, automation, and file handling.",
        "url": "https://automatetheboringstuff.com",
        "provider": "Online Book",
        "category": "TUTORIAL",
        "difficulty": "BEGINNER",
        "duration_minutes": 480,
        "skill_name": "Python",
        "rating": 4.7,
        "enrollment_count": 500000,
    },
    {
        "title": "JavaScript: Understanding the Weird Parts",
        "description": "Deep dive into JavaScript closures, prototypes, and execution context.",
        "url": "https://www.udemy.com/course/understand-javascript",
        "provider": "Udemy",
        "category": "COURSE",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 540,
        "skill_name": "JavaScript",
        "rating": 4.8,
        "enrollment_count": 800000,
    },
    {
        "title": "freeCodeCamp JavaScript Algorithms",
        "description": "Interactive JavaScript challenges covering ES6+, regex, and debugging.",
        "url": "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
        "provider": "freeCodeCamp",
        "category": "COURSE",
        "difficulty": "BEGINNER",
        "duration_minutes": 300,
        "skill_name": "JavaScript",
        "rating": 4.6,
        "enrollment_count": 3000000,
    },
    {
        "title": "React Official Tutorial",
        "description": "Build UIs with React components, state, and hooks from the official team.",
        "url": "https://react.dev/learn",
        "provider": "Meta",
        "category": "TUTORIAL",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 420,
        "skill_name": "React",
        "rating": 4.9,
        "enrollment_count": 1200000,
    },
    {
        "title": "The Complete React Guide",
        "description": "React 18 with hooks, Redux, Next.js, and React Router.",
        "url": "https://www.udemy.com/course/understand-react/",
        "provider": "Udemy",
        "category": "COURSE",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 720,
        "skill_name": "React",
        "rating": 4.7,
        "enrollment_count": 900000,
    },
    {
        "title": "Node.js Crash Course",
        "description": "Build REST APIs with Node.js, Express, and MongoDB.",
        "url": "https://www.youtube.com/watch?v=fBNz5xF-Kx4",
        "provider": "YouTube",
        "category": "VIDEO",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 180,
        "skill_name": "Node.js",
        "rating": 4.6,
        "enrollment_count": 2000000,
    },
    {
        "title": "The Odin Project — NodeJS",
        "description": "Full-stack Node.js path with Express, databases, and authentication.",
        "url": "https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs",
        "provider": "The Odin Project",
        "category": "COURSE",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 600,
        "skill_name": "Node.js",
        "rating": 4.8,
        "enrollment_count": 400000,
    },
    {
        "title": "CS50's Introduction to Computer Science",
        "description": "Harvard's intro CS course — algorithms, data structures, C, Python, SQL, web.",
        "url": "https://cs50.harvard.edu/x/",
        "provider": "Harvard",
        "category": "COURSE",
        "difficulty": "BEGINNER",
        "duration_minutes": 1200,
        "skill_name": "Data Structures",
        "rating": 4.9,
        "enrollment_count": 4000000,
    },
    {
        "title": "Data Structures Easy to Advanced",
        "description": "Full data structures course: arrays, linked lists, trees, graphs, hash maps.",
        "url": "https://www.youtube.com/playlist?list=PL9xmBV_5YoZO1LByyEDqVw6Xw2UBeB7My",
        "provider": "YouTube",
        "category": "VIDEO",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 480,
        "skill_name": "Data Structures",
        "rating": 4.7,
        "enrollment_count": 1500000,
    },
    {
        "title": "SQL Tutorial — Full Database Course",
        "description": "Complete SQL from SELECT to JOINs, indexes, and optimization.",
        "url": "https://www.youtube.com/watch?v=HXV3zeQKqGY",
        "provider": "YouTube",
        "category": "VIDEO",
        "difficulty": "BEGINNER",
        "duration_minutes": 240,
        "skill_name": "SQL",
        "rating": 4.6,
        "enrollment_count": 3000000,
    },
    {
        "title": "PostgreSQL Tutorial",
        "description": "PostgreSQL for beginners: installation, queries, stored procedures, and admin.",
        "url": "https://www.postgresqltutorial.com/",
        "provider": "postgresqltutorial.com",
        "category": "TUTORIAL",
        "difficulty": "BEGINNER",
        "duration_minutes": 360,
        "skill_name": "PostgreSQL",
        "rating": 4.5,
        "enrollment_count": 500000,
    },
    {
        "title": "AWS Cloud Practitioner Essentials",
        "description": "AWS fundamentals: EC2, S3, RDS, IAM, and cloud architecture basics.",
        "url": "https://explore.skillbuilder.aws/learn/course/external/view/elearning/cloud-practitioner-essentials",
        "provider": "AWS",
        "category": "COURSE",
        "difficulty": "BEGINNER",
        "duration_minutes": 300,
        "skill_name": "Cloud Computing",
        "rating": 4.7,
        "enrollment_count": 1800000,
    },
    {
        "title": "Google Cloud Fundamentals",
        "description": "Core GCP services: Compute Engine, Cloud Storage, BigQuery, and Kubernetes.",
        "url": "https://www.coursera.org/learn/gcp-fundamentals",
        "provider": "Coursera",
        "category": "COURSE",
        "difficulty": "BEGINNER",
        "duration_minutes": 240,
        "skill_name": "Cloud Computing",
        "rating": 4.6,
        "enrollment_count": 700000,
    },
    {
        "title": "Machine Learning by Andrew Ng",
        "description": "Stanford's ML course: linear regression, neural networks, SVMs, clustering.",
        "url": "https://www.coursera.org/learn/machine-learning",
        "provider": "Coursera",
        "category": "COURSE",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 900,
        "skill_name": "Machine Learning",
        "rating": 4.9,
        "enrollment_count": 5000000,
    },
    {
        "title": "Fast.ai Practical Deep Learning",
        "description": "Top-down practical approach to deep learning with PyTorch.",
        "url": "https://course.fast.ai/",
        "provider": "fast.ai",
        "category": "COURSE",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 600,
        "skill_name": "Deep Learning",
        "rating": 4.8,
        "enrollment_count": 800000,
    },
    {
        "title": "HTML & CSS Full Course",
        "description": "Complete HTML5 and CSS3 from scratch — responsive design and Flexbox/Grid.",
        "url": "https://www.youtube.com/watch?v=UDrlmZaMO2A",
        "provider": "YouTube",
        "category": "VIDEO",
        "difficulty": "BEGINNER",
        "duration_minutes": 360,
        "skill_name": "HTML/CSS",
        "rating": 4.7,
        "enrollment_count": 4000000,
    },
    {
        "title": "CSS Grid and Flexbox Mastery",
        "description": "Modern CSS layouts with Grid and Flexbox — real-world projects.",
        "url": "https://www.udemy.com/course/css-grid-and-flexbox-mastercourse/",
        "provider": "Udemy",
        "category": "COURSE",
        "difficulty": "BEGINNER",
        "duration_minutes": 180,
        "skill_name": "CSS",
        "rating": 4.6,
        "enrollment_count": 300000,
    },
    {
        "title": "Git & GitHub Crash Course",
        "description": "Version control with Git, branching, merging, and GitHub workflows.",
        "url": "https://www.youtube.com?v=SWYqp7iUP_T",
        "provider": "YouTube",
        "category": "VIDEO",
        "difficulty": "BEGINNER",
        "duration_minutes": 60,
        "skill_name": "Git",
        "rating": 4.7,
        "enrollment_count": 5000000,
    },
    {
        "title": "Pro Git Book",
        "description": "The complete Git reference — from basics to internals and advanced branching.",
        "url": "https://git-scm.com/book/en/v2",
        "provider": "Git SCM",
        "category": "TUTORIAL",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 480,
        "skill_name": "Git",
        "rating": 4.9,
        "enrollment_count": 2000000,
    },
    {
        "title": "Docker for Beginners",
        "description": "Containerize apps with Docker — images, Dockerfiles, Compose, and volumes.",
        "url": "https://www.youtube.com/watch?v=fqMOX6JJhGo",
        "provider": "YouTube",
        "category": "VIDEO",
        "difficulty": "BEGINNER",
        "duration_minutes": 120,
        "skill_name": "Docker",
        "rating": 4.6,
        "enrollment_count": 2500000,
    },
    {
        "title": "Kubernetes Basics",
        "description": "Deploy and manage containerized apps with Kubernetes pods, services, and deployments.",
        "url": "https://www.coursera.org/learn/kubernetes",
        "provider": "Coursera",
        "category": "COURSE",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 300,
        "skill_name": "Kubernetes",
        "rating": 4.5,
        "enrollment_count": 600000,
    },
    {
        "title": "TypeScript for Beginners",
        "description": "TypeScript fundamentals: types, interfaces, generics, and integration with JS.",
        "url": "https://www.youtube.com/watch?v=BwuLxPH8IDs",
        "provider": "YouTube",
        "category": "VIDEO",
        "difficulty": "BEGINNER",
        "duration_minutes": 180,
        "skill_name": "TypeScript",
        "rating": 4.7,
        "enrollment_count": 1200000,
    },
    {
        "title": "REST API Design Best Practices",
        "description": "Design RESTful APIs: naming, versioning, error handling, and pagination.",
        "url": "https://restfulapi.net/",
        "provider": "restfulapi.net",
        "category": "TUTORIAL",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 120,
        "skill_name": "REST APIs",
        "rating": 4.6,
        "enrollment_count": 900000,
    },
    {
        "title": "Agile & Scrum Fundamentals",
        "description": "Learn Agile methodology, Scrum sprints, user stories, and Kanban boards.",
        "url": "https://www.coursera.org/learn/agile-development",
        "provider": "Coursera",
        "category": "COURSE",
        "difficulty": "BEGINNER",
        "duration_minutes": 180,
        "skill_name": "Agile Methodologies",
        "rating": 4.5,
        "enrollment_count": 1000000,
    },
    {
        "title": "TensorFlow Developer Certificate",
        "description": "Build ML models with TensorFlow: CNNs, NLP, time series, and deployment.",
        "url": "https://www.coursera.org/professional-certificates/tensorflow-in-practice",
        "provider": "Coursera",
        "category": "COURSE",
        "difficulty": "ADVANCED",
        "duration_minutes": 1200,
        "skill_name": "TensorFlow",
        "rating": 4.8,
        "enrollment_count": 500000,
    },
    {
        "title": "Linux Command Line Fundamentals",
        "description": "Master the terminal: file navigation, permissions, shell scripting, and grep.",
        "url": "https://www.youtube.com/watch?v=oxuRxZz8nd0",
        "provider": "YouTube",
        "category": "VIDEO",
        "difficulty": "BEGINNER",
        "duration_minutes": 120,
        "skill_name": "Linux",
        "rating": 4.6,
        "enrollment_count": 3000000,
    },
    {
        "title": "Data Analysis with Pandas",
        "description": "Analyze datasets with pandas: filtering, grouping, merging, and visualization.",
        "url": "https://www.youtube.com/watch?v=vmEHCJofslg",
        "provider": "YouTube",
        "category": "VIDEO",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 240,
        "skill_name": "Pandas",
        "rating": 4.7,
        "enrollment_count": 1500000,
    },
    {
        "title": "UX Design Fundamentals",
        "description": "User research, wireframing, prototyping, and usability testing.",
        "url": "https://www.coursera.org/learn/ux-design-fundamentals",
        "provider": "Coursera",
        "category": "COURSE",
        "difficulty": "BEGINNER",
        "duration_minutes": 300,
        "skill_name": "UX Design",
        "rating": 4.6,
        "enrollment_count": 800000,
    },
    {
        "title": "Figma UI Design Tutorial",
        "description": "Design modern UIs in Figma — auto layout, components, and design systems.",
        "url": "https://www.youtube.com/watch?v=jwCmIBJ81tc",
        "provider": "YouTube",
        "category": "VIDEO",
        "difficulty": "BEGINNER",
        "duration_minutes": 360,
        "skill_name": "Figma",
        "rating": 4.8,
        "enrollment_count": 2000000,
    },
    {
        "title": "Cybersecurity Fundamentals",
        "description": "Network security, encryption, OWASP Top 10, and ethical hacking basics.",
        "url": "https://www.coursera.org/learn/cybersecurity-fundamentals",
        "provider": "Coursera",
        "category": "COURSE",
        "difficulty": "BEGINNER",
        "duration_minutes": 420,
        "skill_name": "Cybersecurity",
        "rating": 4.5,
        "enrollment_count": 600000,
    },
    {
        "title": "Communication Skills for Engineers",
        "description": "Technical writing, presentations, team communication, and stakeholder management.",
        "url": "https://www.coursera.org/learn/technical-writing",
        "provider": "Coursera",
        "category": "COURSE",
        "difficulty": "BEGINNER",
        "duration_minutes": 180,
        "skill_name": "Communication",
        "rating": 4.6,
        "enrollment_count": 500000,
    },
    {
        "title": "Problem Solving — HackerRank",
        "description": "Practice coding challenges: arrays, strings, sorting, searching, and graphs.",
        "url": "https://www.hackerrank.com/domains/algorithms",
        "provider": "HackerRank",
        "category": "PRACTICE",
        "difficulty": "INTERMEDIATE",
        "duration_minutes": 300,
        "skill_name": "Problem Solving",
        "rating": 4.5,
        "enrollment_count": 2000000,
    },
]

LEARNING_RESOURCES_TABLE = "learning_resources"


def seed():
    if not db_available():
        print("Database unavailable — skipping learning resources seed.")
        return

    client = get_client()
    if not client:
        print("Supabase client unavailable — skipping.")
        return

    try:
        existing = (
            client.table(LEARNING_RESOURCES_TABLE).select("id").limit(1).execute()
        )
        if existing.data:
            print(
                f"Learning resources already seeded ({len(existing.data)} found). Skipping."
            )
            return
    except Exception:
        pass

    inserted = 0
    for r in RESOURCES:
        try:
            client.table(LEARNING_RESOURCES_TABLE).insert(r).execute()
            inserted += 1
        except Exception as e:
            print(f"  Skip '{r['title']}': {e}")

    print(f"Seeded {inserted}/{len(RESOURCES)} learning resources.")


if __name__ == "__main__":
    seed()
